directories:
  output: dist
  buildResources: build
appId: com.duyi.markdown
productName: Markdown Editor
publish:
  - provider: generic
    url: http://127.0.0.1:3000/
mac:
  category: public.app-category.utilities
dmg:
  title: Markdown Editor
  icon: ./icons
  background: ./assets/background.jpeg
  window:
    width: 660
    height: 400
  contents:
    - x: 180
      'y': 170
    - x: 480
      'y': 170
      type: link
      path: /Applications
pkg:
  installLocation: /Applications
files: []
electronVersion: 28.1.4
